server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10  # Requests per second
                redis-rate-limiter.burstCapacity: 20  # Maximum burst
                key-resolver: "#{@userKeyResolver}"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
